export type CODMWeaponCategory = 
  | "ARMAS_MITICAS"
  | "OPERADORES_MITICOS"
  | "OPERADORES_LEYENDA"
  | "ARMAS_PRESTIGIO"
  | "ARMAS_LEYENDA"
  | "FUSILES_ASALTO"
  | "SUBFUSILES"
  | "FRANCOTIRADORES"
  | "AMETRALLADORAS"
  | "ESCOPETAS"
  | "TIRADOR"
  | "PISTOLAS_Y_CUERPO_A_CUERPO";

export interface CODMWeaponItem {
  name: string;
  category: CODMWeaponCategory;
  isMythic?: boolean;
}

// 🔴 8 Personajes Míticos Oficiales
export const CODM_MYTHIC_OPERATORS: string[] = [
  "KUI JI - GUARDIÁN DEL JURAMENTO ETERNO",
  "NOMBRE EN CLAVE: LAZARUS - COSMIC WRATH",
  "SHEPHERD OSCURO - PHANTOM",
  "SOPHIA - DAWN'S RENEWAL",
  "GHOST - ETERNAL SIEGE",
  "SIREN - SIREN SONG",
  "TEMPLARIO - COUTEAU'S OATH",
  "SPECTRE - T-3",
];

// 🟡 32 Personajes de Leyenda Oficiales (Incluyendo Gundam, Persona 5 y Street Fighter)
export const CODM_LEGENDARY_OPERATORS: string[] = [
  "Reaper - Sazabi",
  "Ethan - Freedom Gundam",
  "Proton - Nu Gundam",
  "Gunzo - Gundam Deathscythe Hell",
  "Cipher - Joker",
  "Rastreadora urbana - Violet",
  "Scylla - Panther",
  "Alias - Queen",
  "Shigenori - Akuma",
  "Fiona St. George - Cammy",
  "Shadowfall - Chun-Li",
  "Hidora Kai - Ryu",
  "Cipher - Resolución Absoluta",
  "Shepherd Oscuro - Astral Marauder",
  "Dame - Break of Dawn",
  "Hidora Kai - Cruel Night",
  "Fiona St. George - Eternal Blizzard",
  "Foxtrot - Deadly Fragments",
  "Richtofen - Dark Designs",
  "Manta Ray - Aquarian Blade",
  "Nyx - Starstruck",
  "Alias - Roboticist",
  "Price - Counter-Terror",
  "Outrider - Techborn",
  "Sophia - Errant Knight",
  "Phantom - Osiris",
  "Firebreak - Basilisk",
  "Gunzo - Devil Jester",
  "Ghost - Retribution",
  "Nikto - Dark Side",
  "Reaper - Ashura",
  "Mace - Final Guard",
];

// 🔴 Las 34 Armas Míticas Oficiales Exactas de CODM
export const CODM_MYTHIC_WEAPONS: string[] = [
  "AK117 - Lava Remix",
  "FSS Hurricane - Horizonte sombrío",
  "DP27 - Relicario necrótico",
  "Lachmann-556 - Forged Calamity",
  "SO-14 - Razor Torrent",
  "Type 25 - Deepstar Piercer",
  "RAM-7 - Nebula's Brush",
  "VMP - Toxic Blooms",
  "LW3-Tundra - Pulsar Chamber",
  "XM4 - Luminescent Jade",
  "USS 9 - Fusion",
  "JAK-12 - Rising Ashes",
  "BP50 - Ion Eruption",
  "MG42 - The Campaign",
  "Type 19 - Celestial Ink",
  "Grau 5.56 - Phantom's Core",
  "CX-9 - Lethal Hollow",
  "AK117 - Grim Ending",
  "FFAR 1 - Bright Blade",
  "QQ9 - Dual Kinetics",
  "DL Q33 - Lotus Flames",
  "EM2 - Eclipse Phaser",
  "Krig 6 - Ice Drake",
  "Switchblade X9 - Neon Legend",
  "Oden - Divine Smite",
  "AK-47 - Radiance",
  "Kilo 141 - Demonsong",
  "CBR4 - Amoeba",
  "M13 - Morningstar",
  "Rytec AMR - Nautilus",
  "Holger 26 - Dark Frontier",
  "AS VAL - Double Edge",
  "Peacekeeper MK2 - Artifact",
  "Fennec - Ascended",
];

// 🟠 Armas de Prestigio Oficiales
export const CODM_PRESTIGE_WEAPONS: string[] = [
  "KN-44 - War Breaker",
  "MAC-10 - Bast Idol",
  "Type 25 - Phoenix Inferno",
  "Arctic .50 - Foxfire de prestigio",
  "SKS - Deathlance",
  "LAPA - N.º 35",
];

// 🟡 Armas de Leyenda y Escopetas Oficiales
export const CODM_LEGENDARY_WEAPONS: string[] = [
  "KRM-262 - Glorious Blaze",
  "KRM-262",
  "BY15 - Point Blank",
  "HS0405 - Stone Crown",
  "R9-0 - Hopper",
  "FR .556 - Superhighway",
  "ICR-1 - Forced Laughter",
  "BK57 - Space Race",
  "Razorback - Necessary Diplomacy",
  "QXR - Secret Santa",
  "DR-H - Wicked Claw",
  ".50 GS - Calamity",
  "AGR 556 - Durandal",
  "M4 - Court Jester",
  "RUS-79U - Dustkicker",
  "GKS - Tactical Unicorn",
  "MSMC - Space Station",
  "AK-47 - Wrath Black & Gold",
  "S36 - Phobos",
  "KN-44 - Color Spectrum",
  "Man-O-War - Dream Crystal",
  "Pharo - Dream Crystal",
  "AK117 - Holidays",
  "DL Q33 - Holidays",
  "Shorty - Last Resort",
  "CR-56 AMAX - Muerte escarlata",
  "Locus - Neptune",
  "MK2 - Helix Grade",
  "Razorback - Boereal Aegis",
  "QQ9 - Sigrún",
  "KN-44 - Dance of Death",
  "ICR-1 - Innovator",
  "PP19 Bizon - Invocation",
  "HG 40 - Estándar de oro",
  "QQ9 - Melting Point",
  "RPD - Practical Joker",
  "LK24 - Justicar",
  "Chopper - Chain Reaction",
  "AK117 - Derretimiento",
  "Outlaw - High Noon",
  "Cordite - Zero G",
  "RUS-79U - ZX 7000",
  "Swordfish - Aquatic Slayer",
  "Kilo 141 - Nova Gold",
  "ZRG 20 mm - Ticket to Hell",
  "PPSh-41 - Combustion",
  "DR-H - Poised Guardian",
  "SKS - Luminary",
  "KN-44 - Mystic Fox",
  "QQ9 - Albatross",
  "ASM10 - Red Shadow",
  "RUS-79U - Equalizer",
  "PP19 Bizon - Homebrewed Hex",
  "DR-H - Blood Rose",
  "Holger 26 - Risen Deep",
  "J358 - Heavy Handed",
  "HBRa3 - Rictus Arc",
  "JAK-12 - Molten Mirror",
  "AS VAL - Steel Fusion",
  "QXR - Fossil Fire",
  "Renetti - Metal Phantom",
  "Arctic .50 - Foxfire",
  "AK-47 - Kuromaku",
  "PDW-57 - Desecho tóxico",
  "Man-O-War - Death Scythe",
  "SP-R 208 - Counter Spy",
  "Type 25 - Bloody Vengeance",
  "GKS - Wanderer",
  "SKS - Particle Splitter",
  "LK24 - Drop Shock",
  "KRM-262 - Glorious Blaze",
  "KSP 45 - Divinity",
  "L-CAR 9 - Industrial Pulverizer",
  "M13 - Liminal Flare",
  "M4 - Thermal Shroud",
  "RPD - Yellowjacket",
  "PDW-57 - Battalion",
  "DL Q33 - Bass Booster",
  "AK-47 - Pumpkin Head",
  "NA-45 - Lycanthrope",
  "HVK-30 - Maximum Security",
  "DL Q33 - Zealot",
  "HBRa3 - Swarm",
  "Echo - Natural Causes",
  "Kilo con mecanismo de cerrojo - Rail Gun",
  "UL736 - Depth Charge",
  "ASM10 - Bunker Buster",
  "Arctic .50 - Zodiac Beast",
  "PPSh-41 - Emberwing",
  "Locus - Electron",
  "Type 25 - Horseman's Pick",
  "D13 Sector - Steam Shredder",
  "PKM - Red Nose Revenge",
  "Ballesta - Kinetic Electricity",
  "SVD - Toxicant",
  "Peacekeeper MK2 - Crustpunker",
  "LK24 - Idol Star",
  "HG 40 - Ghoul Bound",
  "Swordfish - Calaca",
  "Thumper - Surprise Party",
  "Chopper - Rules of the Game",
  "Fennec - Venom Coil",
  "DL Q33 - Advanced Artillery",
  "R9-0 - Hopper",
  "BK57 - Flash Freeze",
  "QQ9 - Moonlight",
  "M4LMG - Salamander",
  "Hades - Void Sender",
  "AK117 - Aesir",
  "MX9 - Heartless",
  "DR-H - Purebred",
  "AGR 556 - Ripper",
  "Type 25 - Magnetic Engine",
  "ASM10 - Abyssal Agent",
  "RPD - Mahogany Shooter",
  "EM2 - Pineapple Crush",
  "Striker 45 - Sharp Fins",
  "BY15 - Boba Blaster",
  "Grau 5.56 - Burned Soul",
  "XPR-50 - Voluntad quebrada",
  "Kilo 141 - Legion's Spear",
  "KSP 45 - Jolted Radio",
  "RUS-79U - Custom Job",
  "Grau 5.56 - Sapphire Fangs",
  "Locus - Icy Claws",
  "RAAL MG - Frostfire",
  "AK-47 - Santa's Little Reaper",
  "Dobvra - Yggdrasil",
  "Argus - True Balance",
  "Buscapremios - Capricornio",
  "Switchblade X9 - Piscis",
  "Groza - Acuario",
  "M13 - Risen Shadow",
  "XPR-50 - Pale Thunder",
  "CX-9 - Vibrant Ashes",
  "M4 - Black Gold Royal",
  "LW3-Tundra - Crimson Jaws",
  "M21 EBR - Rising Ashes",
  "PP19 Bizon - JINGLE-55",
  "RUS-79U - Holiday Lights",
  "CBR4 - Lattice",
  "LAPA - King's Pride",
  "M16 - Targonite-3",
  "ICR-1 - Knock Out",
  "Type 25 - Hell's Horse",
  "Pharo - Submarine-008",
  "SVD - Admiral Star",
  "AK-47 - ICB Rifle",
  "Krig 6 - Sword of the Blue Skies",
  "Tijeras de rayo - Gundam Deathscythe Hell (EW)",
  "Fennec - Axis Miracle",
  "Locus - Red Comet",
  "Sable de rayo - Freedom Gundam",
  "M13 - Glory of Shadows",
  "M1 Garand - Unicorn's Might",
  "AK-47 - The Pray of the End",
  "PP19 Bizon - Will of Ruins",
  "KRM-262 - Red Fissure",
  "MW11 - Scorcher",
  "Vargo-S - Fiery Hell",
  "FFAR 1 - Fire and Fury",
  "Chicom - Density Infinite",
  "BP50 - Liones's Grace",
  "CX-9 - Dragon's Wrath",
  "Rytec AMR - Happy Hammer",
  "Krig 6 - Slick Chrome",
  "AK-47 - Moon Shadow",
  "OTs 9 - Malebranche",
  "Dobvra - Light's Echo",
  "HDR - Persuasion",
  "Peacekeeper MK2 - Vivid Notes",
  "Oden - Lethal Riptide",
  "Kilo 141 - Nano Katana",
  "PDW-57 - Wasteland's End",
  "MG42 - Black Mirror",
  "Man-O-War - Doomfire Pulse",
  "QQ9 - Quantum Flash",
  "VLK Rogue - Evolutionary",
  "Koshka - Demonic",
  "Columna de serpiente",
  "Groza - Severed Flowers",
  "PPSh-41 - Holiday Workshop",
  "Bruen MK9 - Deadly Strings",
  "Arctic .50 - Venetian Scope",
  "Pistola de clavos - Dark Experiments",
  "KN-44 - Shadow's Wings",
  "Maddox - Squash Demon",
  "Holger 26 - Jacked Lantern",
  "Oden - Gripped Chaos",
  "UL736 - Electric Light",
  "CR-56 AMAX - Twisted Visions",
  "Dingo - Scarlet Oracle",
  "AS VAL - Beijing Operatic",
  "MAC-10 - Dragon's Might",
  "M13 - Carrot Cutie",
  "FR .556 - Geo-Blaster 3000",
  "Hades - Serpentine",
  "SP-R 208 - Dual Persona",
  "Locus - Metal Whiskers",
  "Rytec AMR - Gilded Porcelain",
  "M16 - Peacock's Cry",
  "Argus - Carmine Flare",
  "Sai - Rare Divinity",
  "Chopper - Hell Dog",
  "CR-56 AMAX - Bass Drop",
  "Macana paralizante - Surge Baton",
  "LK24 - Arsène",
  "RAM-7 - Cendrillon",
  "Type 63 - Johanna",
  "QQ9 - Carmen",
  "Cuerpo a cuerpo táctica - Virgo",
  "KN-44 - Cargador de tierra",
  "VLK Rogue - Cáncer",
  "RAAL MG - Leo",
  "Man-O-War - Aries",
  "Sten - Resplandor de Starlight",
  "DR-H - Orgullo patriótico",
  "DL Q33 - Sombra de Noir",
  "Fusil de tres líneas - Promesa verde",
  "HVK-30 - Destrucción del titán",
  "Chopper - B.E.A.S.T.",
  "Swordfish - Aberración al acecho",
  "MG82 - Emergencia fría",
  "CX-9 - Circuito vital",
  "MX Guardian - Emergencia crítica",
  "Oden - Quantum Impact",
  "HVK-30 - Polar Circuit",
  "VMP - Crimson Sparkfire",
  "Type 19 - Ride at Dawn",
  "LC10 - Glacial Ash",
  "EM2 - Frigid Dominion",
  "LAG 53 - Aether Fracture",
  "ASM10 - Martial Prime",
  "Vargo-S - Famine's Curse",
  "LW3-Tundra - Delta Red Assault",
  "MG42 - Shun Goku Satsu",
  "USS 9 - Soten Ranka",
  "Grau 5.56 - Shin Shoryuken",
  "KN-44 - Augmented Atomizer",
  "Arctic .50 - Corrupting Conduit",
  "Oden - Victor's Firebrand",
  "ICR-1 - Wisterian Visage",
  "M4 - Jupiter Cannon",
  "M4 - Shackle's Bite",
  "AK117 - Molting Mauler",
  "Kilo 141 - Skull Screamer",
  "CX-9 - Sugarsweet Screamer",
  "R9-0 - Howl Cannon",
  "ISO - First Protocol",
  "MAC-10 - Kitty in Pink",
  "M4LMG - Cold Claws Kingdom",
  "Type 19 - Cold Claws Capper",
  "ICR-1 - Purrfect Pulverizer",
  "JAK-12 - Briny Deep",
  "USS 9 - Spectral Seas",
  "Grau 5.56 - Immense Tides",
  "ASM10 - Girls' Frontline ASM10",
  "AS VAL - Shadow Marksman",
  "RPD - Juicio del destino",
  "FHJ-18 - Shattered Chaos",
  "DR-H - Charioteer",
  "Type 19 - Deadly Gravity",
  "Type 63 - Anchor Weighed",
  "HVK-30 - Dantang's Diancui",
  "Holger 26 - Ice Majesty",
  "LAG 53 - Rift Collapse",
  "HDR - Last Laugh",
];

export const CODM_BASE_WEAPONS: Record<CODMWeaponCategory, string[]> = {
  ARMAS_MITICAS: CODM_MYTHIC_WEAPONS,
  OPERADORES_MITICOS: CODM_MYTHIC_OPERATORS,
  OPERADORES_LEYENDA: CODM_LEGENDARY_OPERATORS,
  ARMAS_PRESTIGIO: CODM_PRESTIGE_WEAPONS,
  ARMAS_LEYENDA: CODM_LEGENDARY_WEAPONS,
  FUSILES_ASALTO: [
    "AK-47", "M13", "Kilo 141", "Grau 5.56", "Oden", "Type 19", "FFAR 1", "EM2", "Krig 6", "BP50", "XM4", "Type 25", "RAM-7", "Lachmann-556", "Groza", "Lag 53", "Peacekeeper MK2", "AS VAL", "CR-56 AMAX", "KN-44", "LK24", "BK57", "ICR-1", "HBRa3", "M16", "AK117", "Man-O-War", "DR-H", "HVK-30", "Maddox", "M4", "FR .556", "Swordfish", "Vargo-S", "Type 63", "M1 Garand"
  ],
  SUBFUSILES: [
    "Switchblade X9", "CX-9", "USS 9", "ISO", "TEC-9", "Fennec", "CBR4", "PP19 Bizon", "QQ9", "VMP", "AGR 556", "QXR", "RUS-79U", "PDW-57", "Razorback", "MSMC", "HG 40", "Pharo", "GKS", "Cordite", "MX9", "KSP 45", "LAPA", "Ots 9", "Striker 45", "PPSH-41", "MAC-10", "Sten", "LC10"
  ],
  FRANCOTIRADORES: [
    "OP27", "DL Q33", "Locus", "LW3-Tundra", "Arctic .50", "Outlaw", "Rytec AMR", "SVD", "ZRG 20mm", "HDR", "Koshka", "XPR-50", "M21 EBR", "NA-45", "Fusil de tres líneas"
  ],
  AMETRALLADORAS: [
    "MG42", "Chopper", "RPD", "M4LMG", "UL736", "S36", "Holger 26", "Hades", "Dingo", "Bruen MK9", "PKM", "RAAL MG", "MG82"
  ],
  ESCOPETAS: [
    "JAK-12", "KRM-262", "BY15", "HS0405", "Striker", "HS2126", "Echo", "Argus", "R9-0", "VLK Rogue", "MX Guardian"
  ],
  TIRADOR: [
    "SO-14", "Kilo Bolt-Action", "SKS", "SP-R 208", "MK2"
  ],
  PISTOLAS_Y_CUERPO_A_CUERPO: [
    ".50 GS", "J358", "MW11", "Renetti", "L-CAR 9", "Dobvra", "Shorty", "Katana", "Kali Sticks", "Butterfly Knife", "Sais", "Spear", "Machete", "Pistola de clavos", "Thumper", "FHJ-18", "D13 Sector", "Ballesta"
  ],
};

export function getAllCODMWeaponsList(): string[] {
  const allWeapons = new Set<string>();
  Object.values(CODM_BASE_WEAPONS).forEach(list => {
    list.forEach(w => allWeapons.add(w));
  });
  return Array.from(allWeapons).sort();
}
